Repository nextcloud/backup, pull requests merged in 2021-12, with the labels that each got.

#98 ignore exception on external appdata
  lib/Command/Reset.php
Labels: review needed

#86 lock during download/upload
  lib/Command/PointDownload.php
  lib/Command/PointUpload.php
  lib/Db/PointRequest.php
  lib/Service/UploadService.php
Labels: bug, enhancement, review needed

#100 +cron_enabled
  lib/Service/ConfigService.php
  lib/Service/CronService.php
Labels: enhancement, review needed

#94 generate local log file
  lib/Command/PointCreate.php
  lib/Command/PointPack.php
  lib/Command/PointUnpack.php
  lib/Command/PointUpload.php
  lib/Cron/Backup.php
  lib/Cron/Manage.php
  lib/Service/ConfigService.php
  lib/Service/OutputService.php
  lib/Service/PointService.php
  lib/Wrappers/AppDataRootWrapper.php
Labels: enhancement, review needed

#105 Add "Enable background tasks" section
  src/components/GeneralSettingsSection.vue
  src/models/SettingsModel.js
Labels: enhancement

#99 lock during cron jobs
  lib/Cron/Backup.php
  lib/Cron/Event.php
  lib/Cron/Manage.php
  lib/Exceptions/JobsTimeSlotException.php
  lib/Service/ChunkService.php
  lib/Service/ConfigService.php
  lib/Service/CronService.php
  lib/Service/ExternalFolderService.php
  lib/Service/PackService.php
  lib/Service/UploadService.php
Labels: bug, enhancement

#129 ignoring default apps folder when working on custom_apps
  lib/Service/PointService.php
Labels: bug, review needed

#128 +prepareStorageConfig
  lib/Service/ExternalFolderService.php
Labels: bug, review needed
