Repository nextcloud/backup, pull requests merged in 2021-11, with the labels that each got.

#38 Add App Data section
  js/backup-adminSettings.js
  js/backup-adminSettings.js.map
  src/components/AppDataSection.vue
  src/components/ExternalLocationsSection.vue
  src/components/RestoringPointHealthIcon.vue
  src/components/RestoringPointsListSection.vue
  src/views/BackupAdminSettings.vue
Labels: enhancement

#48 Fix php CS
  lib/Service/PackService.php
  lib/Service/PointService.php
Labels: bug

#50 Improve restoring point rendering
  js/backup-adminSettings.js
  js/backup-adminSettings.js.map
  src/components/AppDataSection.vue
  src/components/RestoringPointsListSection.vue
  src/models/RestoringPointModel.js
  src/views/BackupAdminSettings.vue
Labels: bug, enhancement

#57 unset deprecated external appdata
  lib/Command/ExternalAppData.php
Labels: review needed

#56 renaming to --all-storages
  lib/Command/PointArchive.php
  lib/Command/PointComment.php
  lib/Command/PointDelete.php
  lib/Command/PointUnarchive.php
  lib/Service/OccService.php
Labels: review needed

#55 display database type
  lib/Command/PointList.php
Labels: review needed

#59 display resume
  lib/Command/PointRestore.php
Labels: review needed

#61 Update npm and node engines versions
  package.json
Labels: dependencies

#63 activity l10n
  lib/Activity/Provider.php
  lib/Command/PointList.php
Labels: enhancement, review needed

#54 add comment on ./occ backup:point:create
  lib/Command/PointCreate.php
  lib/Service/PointService.php
Labels: review needed

#82 wording incremental -> differential
  README.md
  lib/Command/PointCreate.php
  lib/Command/PointRestore.php
  lib/Controller/LocalController.php
  lib/Cron/Backup.php
  lib/Service/CronService.php
  lib/Service/PointService.php
  screenshots/settings_external_appdata.png
Labels: review needed

#80 remove cs-fixer.cache
  .gitignore
  .php-cs-fixer.cache
Labels: review needed

#68 refresh lock more frequently during packing/unpacking
  lib/Model/RestoringPoint.php
  lib/Service/PackService.php
Labels: enhancement, review needed

#81 comment as optional argument instead of option
  lib/Command/PointCreate.php
Labels: review needed

#83 List of small fixes/improvement
  lib/Command/PointList.php
  lib/Cron/Backup.php
  lib/Cron/Manage.php
  lib/Service/ConfigService.php
  lib/Service/FilesService.php
Labels: review needed
