Repository nextcloud/backup, pull requests merged in 2022-08, with the labels that each got.

#382 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#385 Update npm and node engines versions
  package.json
Labels: dependencies

#395 Put restore point content upon new file creation
  lib/Service/ExternalFolderService.php
Labels: backport-request

#397 better upload
  lib/Service/ExternalFolderService.php
  lib/Service/PackService.php
  lib/Service/PointService.php
  lib/Service/UploadService.php
  lib/Tools/ActivityPub/NCSignature.php
  lib/Tools/Traits/TNCSignatory.php
Labels: backport-request

#400 .noindex
  lib/Service/ExternalFolderService.php
  lib/Service/PointService.php
Labels: backport-request

#399 fix stream from sqldump zip file
  lib/Command/PointRestore.php
  lib/Service/ChunkService.php
Labels: bug

#413 Cleanup package.json
  .github/workflows/dependabot-approve-merge.yml
  package-lock.json
  package.json
  src/adminSettings.js
  src/components/AppDataSection.vue
  src/components/ExternalLocationsSection.vue
  src/components/GeneralSettingsSection.vue
  src/components/RestoringPointsListSection.vue
  src/views/BackupAdminSettings.vue
Labels: dependencies
